name: benchmark_generator
version: 0.0.2
description: >
  Use it to generate identical applications for different frameworks or
  different versions of the same framework to compare various characteristics
  such as code size, runtime performance, etc.
authors:
- Yegor Jbanov <yjbanov@google.com>
homepage: https://github.com/angular/benchmark_generator
environment:
  sdk: '>=1.11.1'
dependencies:
  args: '^0.13.2'
  boilerplate: '^0.1.1'
  quiver: '^0.21.4'
  path: '^1.3.6'
  yaml: '>=2.0.1 <3.0.0'
dev_dependencies:
  test: '^0.12.3'
executables:
  bench_gen: generate
